### PR TITLE
added method to check Group Values

### PR DESCRIPTION
**Pull request by LiamBrennan-UCSB**

### CODE REVIEW

**Comment by jrfarah** [comment]
Great work! A few very minor comments:

- Please add a description for the pull request.
- The docstring for the function `ConfigurationObject.print_group()` in the file `quantive/config.py` seems to have incorrect arguments (the `key` argument is not implemented). Please specify as well in the docstring that the function prints a chosen group of the configuration object and not just the whole thing.
- Please update the documentation to include your contributions by running `python -m quantive options`, choosing `makedocs`, and adding the updated documentation files to your commit.

Thanks!

**Comment by LiamBrennan-UCSB** [comment]
Added a feature to print the keys and values from a chosen group

**Comment by jrfarah** [comment]
Looks great, thanks @LiamBrennan-UCSB!

**Comment by LiamBrennan-UCSB** [comment]
added the changes to the docs

**Pull request merged**
